### ISSUE TITLE
Flags for install/uninstall

### ISSUE THREAD

**Issue by ralt** [Zirak/pkgfs#1]
I propose just adding `-y|--yes` to force install. Or simply use something akin to `apt-get install $@`

**Comment by Zirak** [comment]
I'm for a force option, but against passing the arguments verbatim. That leads to inconsistencies, depending on what your package manager is.
If one wants to do some action which requires a flag, and it makes sense for all package managers to implement, then we should support it (like `--yes`). Anything more esoteric means one should defer to the package manager they assume they'll be using.

**Comment by ralt** [comment]
Fair enough.

**Comment by ralt** [comment]
Is there the concept of signed packages on pacman?

**Comment by Zirak** [comment]
[Does it ever](https://wiki.archlinux.org/index.php/DeveloperWiki:Package_signing). It's a cause of many-a weird upgrade bugs, where for instance the keyring (which is a package) got updated, but you try to install other packages first based off of the old keyring and no fun...
_cough_ Anyway, are you thinking about a flag specifying a "strictness" level?

**Comment by ralt** [comment]
Because debian needs both `--yes` and `--force-yes` if a repo managing the package isn't signed.

**Comment by Zirak** [comment]
Oh my...is this a common occurrence?

**Comment by ralt** [comment]
No. I encountered it because I have a custom repository (with custom packages) and I didn't want to bother signing it.

Aside from that, I haven't seen it a lot out there in the wild.

**Comment by Zirak** [comment]
Added `-y` flag in af631ed3aadf0509e53d5e3f1995309939252a41
