### ISSUE TITLE
Installed directory chapter

### ISSUE THREAD

**Issue by ralt** [Zirak/pkgfs#2]
Imho it should just go out. pkgfs is _not_ a package manager, and handling the deletion of dependencies or not is the job of a package manager.

**Comment by Zirak** [comment]
The interesting point is what're the usual defaults. Under pacman, you have to specify a flag to ensure you didn't leave orphans.
How does apt behave? How does yum? Zypper?

**Comment by ralt** [comment]
apt/yum have a similar flag to remove orphans too, but you can also just run a command later to do so.

But yeah, I got what you mean. To think about.

**Comment by Zirak** [comment]
Somewhen we thought about a `/pkg/orphans/` directory. It could be cool for this and other reasons as well.
