### ISSUE TITLE
"Assorted pains in the side" chapter

### ISSUE THREAD

**Issue by ralt** [Zirak/pkgfs#3]
Should go away too.

**Comment by Zirak** [comment]
It should go away, but with a proper explanation.

The "assorted pans in the side" chapter at this time of writing only has one section dealing with naming conflicts between repositories. For instance, Debian 7's repos may contain `foobin` but Centos 6 can contain the exact same package, only named `foo-bin`.

While it's a real problem with cross-platform package management, the source of the problem isn't disparity among package managers, it's disparity among package repositores. pkgfs doesn't aim to provide a bridge between repositores. A child project may emerge in the future which will attempt to do so (somehow), and it might somehow integrate into pkgfs, but that's a separate effort.
